services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./stylesheets:/app/stylesheets
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
        - ./stylesheets:/app/stylesheets