<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:fo="http://www.w3.org/1999/XSL/Format">
  <xsl:output method="xml" indent="yes"/>
  
  <!--Global variables-->
  <xsl:variable name="list_label" select="'- '"/>
  <xsl:variable name="list_label2" select="'-- '"/>
  <xsl:variable name="new_line" select="'&#10;'"/>
  <xsl:variable name="list_break" select="'#'"/>

  
  <!-- STYLESHEET GOES HERE -->
  
  <xsl:template match="/">
    <fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:fox="http://xmlgraphics.apache.org/fop/extensions" xml:lang="en">
      
      <fo:layout-master-set>
        <fo:simple-page-master master-name="clean_report" page-height="11in" page-width="8.5in" margin="0.5in">
          <fo:region-body margin-bottom="0.65in" margin-top="0.85in"/>
          <fo:region-before extent="0.75in"/> 
          <fo:region-after extent="0.65in"/>
        </fo:simple-page-master>
      </fo:layout-master-set>
      
      <fo:declarations>
        <x:xmpmeta xmlns:x="adobe:ns:meta/">
          <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
            <rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/">
              <dc:title>Standards Report</dc:title>
              <dc:creator>Joint Commission Global Accredtation and Surevey Methods Department</dc:creator>
            </rdf:Description>
          </rdf:RDF>
        </x:xmpmeta>
      </fo:declarations>
      
      
      <fo:page-sequence master-reference="clean_report" id="clean_report">
        <fo:title>Standards Report</fo:title>
        
        
        <!--Header infromation --> 
        <fo:static-content flow-name="xsl-region-before" role="artifact">
          <fo:block-container absolute-position="absolute">
            <xsl:choose> 
              <xsl:when test = "REPORT/ORG = 'JCI'">
                <fo:block><fo:external-graphic src="stylesheets\images\JCI_logo_RGB_TM.png"  content-width = "120" content-height = "24" fox:alt-text="Joint Commission International Logo"/></fo:block>
              </xsl:when>
              <xsl:otherwise>
                <fo:block><fo:external-graphic src="stylesheets\images\327660034JC_logo_RGB_TM.svg"  content-width = "120" content-height = "24" fox:alt-text="Joint Commission Logo"/></fo:block>
              </xsl:otherwise>
            </xsl:choose>
          </fo:block-container>
          <fo:block-container text-align="left" font-family="Satoshi-Bold" font-size="18pt">
            <fo:block start-indent="2in" margin-right="1.25in"><xsl:value-of select="REPORT/TITLE"/></fo:block>
          </fo:block-container>
          <fo:block><fo:leader leader-pattern="rule" rule-thickness="1.5pt" color="gray" leader-length="100%"/></fo:block>
        </fo:static-content>
        
        
        <!--Footer information -->
        <fo:static-content flow-name = "xsl-region-after" role="artifact" font-family="Inter-Regular" font-size="8pt">
          <fo:block><fo:leader leader-pattern="rule" rule-thickness="1pt" color="black" leader-length="100%"/></fo:block>
          <fo:table table-layout="fixed" width="100%">
            <fo:table-column column-width="30%"/>
            <fo:table-column column-width="40%"/>
            <fo:table-column column-width="30%"/>
            <fo:table-body>
              <fo:table-row>
                <fo:table-cell display-align="center"> 
                  <fo:block color="red">Not for Redistribution</fo:block>
                </fo:table-cell>
                <fo:table-cell display-align="center">
                  <fo:block text-align="center">Page <fo:page-number/> of <fo:page-number-citation-last ref-id="clean_report"/></fo:block>
                  <fo:block text-align="center">Report Generated by GACPD</fo:block>
                  <fo:block text-align="center"><xsl:value-of select="REPORT/RUN_DT"/></fo:block>
                </fo:table-cell>
                <fo:table-cell display-align="center">
                  <fo:block text-align="right">© <xsl:value-of select="substring(REPORT/RUN_DT, string-length(REPORT/RUN_DT) - 3)"/> Joint Commission</fo:block>
                </fo:table-cell>
              </fo:table-row>
            </fo:table-body>
          </fo:table>
        </fo:static-content>
        
        <!-- Body of standards report layout -->
        <fo:flow flow-name = "xsl-region-body" font-family="Inter-Regular" font-size="10pt" space-after="5pt">
          <xsl:for-each select="REPORT/PROGRAM/CHAPTER">
                <fo:table page-break-before="always" table-layout="fixed" width="100%" border-bottom="1pt solid gray" space-after="16pt">
                  <fo:table-column column-width="15%"/>
                  <fo:table-column column-width="85%"/>
                  <fo:table-body>
                    <fo:table-row>
                      <fo:table-cell role="TH" number-columns-spanned="2" padding-bottom="5pt">
                        <fo:block font-family="Satoshi-Bold" text-decoration="underline" font-size="16pt" space-after="5pt" color = "#1F336B" role="H1" keep-with-next.within-page="always">
                          <xsl:value-of select="CHAPTER_NM"/> (<xsl:value-of select="CHAPTER_LBL"/>)
                        </fo:block>
                      </fo:table-cell>
                    </fo:table-row>
                
                    <xsl:for-each select="STANDARD">
                      <fo:table-row>
                        <fo:table-cell role="TD" padding-top="5pt" padding-bottom="5pt" display-align="before">
                          <fo:block font-family="Satoshi-Bold" font-size="12pt" space-after="5pt" role="H2" >
                            <xsl:value-of select="STANDARD_NM"/>
                          </fo:block>
                        </fo:table-cell>
                        <fo:table-cell role="TD" padding-top="5pt" padding-bottom="5pt" display-align="before">
                          <fo:block><xsl:value-of select="STD_TX"/></fo:block>
                        </fo:table-cell>
                      </fo:table-row>
                    </xsl:for-each>
                  </fo:table-body>
                </fo:table>
          </xsl:for-each>
        </fo:flow>
      </fo:page-sequence>
    </fo:root>
  </xsl:template>
  


</xsl:stylesheet>
